const data = [{
    title: '订单管理',
    value: 'orderManage',
    checked: [],
    checkAll: false,
    indeterminate: false,
    children: [{
        title: '订单管理',
        value: 'orderList'
    }, {
        title: '评价管理',
        value: 'comments'
    }, {
        title: '投诉管理',
        value: 'complaints'
    }, {
        title: '订单详情',
        value: 'orderDetail'
    }]
}, {
    title: '护工管理',
    value: 'workerManage',
    checked: [],
    checkAll: false,
    indeterminate: false,
    children: [{
        title: '护工列表',
        value: 'list'
    }, {
        title: '护工小组',
        value: 'group'
    }, {
        title: '完善信息',
        value: 'perfectly'
    }, {
        title: '小组订单',
        value: 'teamOrders'
    }, {
        title: '押金管理',
        value: 'deposit'
    }, {
        title: '护工奖惩记录',
        value: 'disciplinary'
    }, {
        title: '借款管理',
        value: 'borrow'
    }, {
        title: '介绍人报表',
        value: 'references'
    }]
}, {
    title: '基础数据管理',
    value: 'basicData',
    checked: [],
    checkAll: false,
    indeterminate: false,
    children: [{
        title: '医院管理',
        value: 'hospital'
    }, {
        title: '服务管理',
        value: 'serve'
    }, {
        title: '员工管理',
        value: 'employee'
    }, {
        title: '床位管理',
        value: 'sickbed'
    }, {
        title: '基本信息设置',
        value: 'basicinfo'
    }, {
        title: '客户管理',
        value: 'customer'
    }, {
        title: '客户详情',
        value: 'customerDetails'
    }]
}, {
    title: '统计分析',
    value: 'statistics',
    checked: [],
    checkAll: false,
    indeterminate: false,
    children: [{
        title: '流水表',
        value: 'waterTable'
    }, {
        title: '收入详情',
        value: 'income'
    }, {
        title: '派工一览',
        value: 'dispatch'
    }, {
        title: '科室统计',
        value: 'department'
    }, {
        title: '科室详情',
        value: 'departmentDetails'
    }, {
        title: '结算统计',
        value: 'settlement'
    }, {
        title: '预收统计',
        value: 'advance'
    }, {
        title: '考勤表',
        value: 'attendance'
    }, {
        title: '日报表',
        value: 'dailyReport'
    }, {
        title: '现场工作情况',
        value: 'fieldWork'
    }]
}, {
    title: '分账统计',
    value: 'collect',
    checked: [],
    checkAll: false,
    indeterminate: false,
    children: [{
        title: '中期结算',
        value: 'interimSettle'
    }, {
        title: '收入明细',
        value: 'incomeDetails'
    }, {
        title: '确认收入预览',
        value: 'incomeConfirm'
    }, {
        title: '生成薪资',
        value: 'salary'
    }, {
        title: '薪资明细',
        value: 'salaryDetails'
    }, {
        title: '薪资审核',
        value: 'salaryAudit'
    }, {
        title: '薪资发放',
        value: 'payroll'
    }, {
        title: '薪资补发',
        value: 'payback'
    }]
}, {
    title: '角色权限管理',
    value: 'roleManage',
    checked: [],
    checkAll: false,
    indeterminate: false,
    children: [{
        title: '角色管理',
        value: 'role'
    }, {
        title: '角色权限',
        value: 'permission'
    }]
}]

export default data
